services:
    zookeeper:
        image: zookeeper:3.6
        container_name: zookeeper
        ports:
            - '2181:2181'
        networks:
            - local

    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_LOG_DIRS: /kafka/kafka-logs
            KAFKA_BROKER_ID: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - local

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - '8080:8080'
        environment:
            KAFKA_CLUSTERS_0_NAME: local-kafka
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
        depends_on:
            - kafka
            - zookeeper
        networks:
            - local

networks:
    local:
        external: true
