version: '3'
services:
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
            - '9092:9092'
        environment:
            # Identificação do Broker
            KAFKA_BROKER_ID: 1

            # Utilização do modo KRaft (sem Zookeeper)
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

            # Diretórios para logs do Kafka
            KAFKA_LOG_DIRS: /var/lib/kafka/data

            # Configurações de metadata
            KAFKA_METADATA_LOG_DIR: /var/lib/kafka/metadata
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

            # Tópicos de controle interno
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

            # Intervalo de metadados
            KAFKA_MIN_INSYNC_REPLICAS: 1

        volumes:
            - ./data:/var/lib/kafka
